<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<link href="Style/Home.css" rel="stylesheet">

<style type="text/css">
footer {
	position: absolute;
	top: 17550px;
	left: 0;
	width: 100%;
	height: 490px;
	background: #333;
}

footer h4, h5 {
	color: white;
	font-weight: normal;
	margin: 50px 50px;
	font-size: 15px;
}

footer ul {
	margin: 50px 50px;
}

footer li {
	margin: 20px;
	font-size: 12px;
	color: #ccc;
}

footer hr {
	margin: 0px 50px;
	width: 92%;
	border: none;
	height: 1px;
	background: #999;
}

footer table {
	position: absolute;
	top: 100px;
	left: 900px;
	list-style: none;
}

table tr td {
	font-size: 13px;
	padding: 20px;
	color: #fff;
}
</style>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Terms & Condition | Privacy Policy</title>

<script src="http://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="js/jquery-2.1.4.js"></script>
</head>
<body bgcolor="#ccc">

<a href="#" class="back-to-top">TOP</a>


	<div class="header1">



		<a href="#" style="border: none;">BOOKING STATUS </a> <a href="#">CANCELLATION
		</a> <a href="Enquiry.php">ENQUERY </a>
	</div>
	<div class="header2">


		<a href="#">FAQ </a> <a href="ContactUs.php">CONTACT US </a> <a
			href="Tariffs.php">TARIFFS </a> <a href="Gallery.php">GALLERY</a> <a href="Service.php">SERVICES
		</a> <a href="BookCab.php">BOOK FOR RIDE</a> <a href="HomePage.html">HOME
		</a>
	</div>

	<div class="termsHeader">
		<h1>CUSTOMER TERMS AND CONDITIONS</h1>
		<hr>
	</div>

	<div class="termsPanel">
		<p>These customer terms and conditions (T&Cs) apply to Your access
			to, and use of the XXX Application. The Application is operated by
			ANI Technologies Private Limited, and its subsidiaries, licensees,
			and affiliated companies. This document is an electronic record in
			terms of Information Technology Act, 2000 and rules there under as
			applicable and the provisions pertaining to electronic records in
			various statutes as amended by the Information Technology Act, 2000.
			This electronic record is generated by a computer system and does not
			require any physical or digital signatures. By continuing usage of
			the Application, You are consenting to be bound by these T&Cs for use
			and access of the Application. PLEASE ENSURE THAT YOU READ AND
			UNDERSTAND ALL THESE T&Cs BEFORE YOU USE ANY OF THE SERVICES OFFERED
			ON THE APPLICATION, BECAUSE YOU Shall BE BOUND BY ALL THE TERMS AND
			CONDITIONS CONTAINED HEREIN. If You do not accept any of the Customer
			Terms and Conditions, then please don’t use the Application or avail
			any of the Services being provided therein. YOUR AGREEMENT TO THESE
			T&Cs Shall OPERATE AS A BINDING AGREEMENT BETWEEN YOU AND XXX IN
			RESPECT OF THE SERVICES OFFERED/AVAILED USING THE SITE.</p>

		<h4>Definitions</h4>
		<p>
			All of the defined and capitalized terms in these T&Cs will have the
			meaning assigned to them here below:<br> <br> <span>Account</span>
			<br>Refers to the account created by the Customer on the
			Application to become the member of a Community or a Deemed Community
			or a Registered Community or an Open Community.<br> <br> <span>Act</span><br>
			Means the Motor Vehicle Act, 1988 and the rules made there under in
			the City of Operation and includes any amendment, modification or
			re-enactment of the same, or any other succeeding enactment for the
			time being in force.<br> <br> <span>Applicable Laws</span><br>
			Shall mean and include all applicable statutes, enactments, acts of
			legislature or parliament, laws, ordinances, rules, by-laws,
			regulations, notifications, guidelines, policies, directions,
			directives and orders of any governmental authority, tribunal, board,
			or a court of India.<br> <br> <span>Application</span><br>
			Shall mean the feature/category-icon “XXX SHARE” within the mobile
			application “XXX CABS” as may be updated by XXX from time to time.<br>
			<br> <span>Authorized Driver</span><br> Shall mean and
			include such individuals as may be evaluated, appointed and trained
			by the Authorized Vehicle Operator to provide the transportation
			services on behalf of the Authorized Vehicle Operator in accordance
			with the terms & conditions applicable to Authorized Vehicle
			Operators and Applicable Law.<br> <br> <span>Authorized
				Vehicle Operator</span><br> Shall mean and include such individuals
			and agencies which hold valid Contract Carriage Permit(s).<br> <br>
			<span>CSP</span><br> Shall mean an Authorized Driver and/or an
			Authorized Vehicle Operator, offering the service of transporting
			Customers within the City of Operation from the pick up points to the
			drop points as communicated by the Customer at the time of requesting
			the booking on the Application. <br> <br> <span>City
				of Operation</span><br> Sall mean a city in which XXX SHARE has been
			launched and the Customers and CSPs avail and render the
			transportation services respectively. For clarity, the services
			rendered by the CSPs and availed by the Customers Shall be in the
			same city. <br> <br> <span>Community</span><br> Shall
			mean an association of persons having the same domain names in their
			email ids as created by their Recognized Entities, provided that such
			domain names are registered in the name of the Recognized Entities. <br>
			<br> <span>Contract Carriage Permit</span><br> Shall mean
			the valid and subsisting permit/license granted to the Authorized
			Vehicle Operator by the transport authority in the City of Operation
			for plying the Vehicle under Contract Carriage. <br> <br> <span>Co
				– Passenger(s)</span><br> Shall mean and include such Customer(s) who
			is/are also a part of the same Community/Registered Community/Deemed
			Community/Open Community as Yours with whom You will be sharing the
			ride/trip. <br> <br> <span>Customer/ You</span><br>
			Means a person who has an Account on the Application. <br> <br>
			<span>Deemed Community</span><br> Shall mean an association of
			persons not having the same domain names in their email ids, however
			grouped together as a community for the purposes of these T&Cs at the
			sole discretion of XXX. <br> <br> <span>Email ID</span><br>
			Shall mean Your current, active and valid email id, the same being
			created by the Recognized Entity and used by You. XXX Shall use this
			Email ID only for the purpose of Customer verification and consequent
			grouping of Customers in Communities or Registered Communities. <br>
			<br> <span>ETA</span><br> Shall mean the estimated time of
			arrival of the Vehicle, at the pick up point of the Customer,
			provided by XXX before the Ride, which Shall change from time to
			time. <br> <br> <span>ETT</span><br> Shall mean the
			estimated travel time of the Ride, provided by XXX during the Ride,
			which Shall change from time to time. <br> <br> <span>XXX/
				We/ Our/ Us</span><br> Means ANI Technologies Private Limited, a
			company registered under the Companies Act, 1956 and having its
			corporate office at 4th Floor, Cherry Hills Building, Embassy Golf
			Links Business Park, Koramangala Inner Ring Road, Domlur, Bangalore
			560071. <br> <br> <span>Open Community</span><br>
			Shall mean an association of persons who may not have Email IDs or
			the same domain names in their email ids or any other commonality,
			however grouped together as a community for the purposes of these
			T&Cs, at the option of the Customers. <br> <br> <span>Original
				ID</span><br> Shall mean Your current, active and valid email id, the
			same being registered with Us by You for using and accessing the
			mobile application XXXCABS. <br> <br> <span>Recognized
				Entity</span><br> Shall mean a validly existing legal entity carrying
			on activity, which is permitted under Applicable Law, and have the
			power and authority to create and grant the Customer email-ids with
			such domain names as are registered in its name. <br> <br>
			<span>Registered Community</span><br> Shall mean an association
			of persons belonging to a Recognized Entity that has entered into
			special service level arrangements/agreements with XXX. <br> <br>
			<span>Registration Data</span><br>Shall mean and may include the
			present, valid, true and accurate name, Original ID, Email ID, age
			and such other information as may be required by XXX from time to
			time, provided by the Customer at the time of registration on the
			Application. <br> <br> <span>Ride</span><br> Shall
			mean the travel in the Vehicle by the Customer from the Pick Up point
			to the Drop point, facilitated through the Application. <br> <br>
			<span>Service(s)</span><br> Means the facilitation of
			transportation service by CSPs through the Application, within the
			City of Operation. <br> <br> <span>Vehicle</span><br>
			Shall mean a Motorcab as defined under the Motor Vehicles Act, 1988.
			<br> <br> <span>You, Your or Yourself</span><br> Shall
			mean reference to the Customer accessing the Application
		</p>

		<H4>Interpretation</H4>

		<ul>
			<li>Any reference to the singular includes a reference to the
				plural and vice versa, unless explicitly provided for otherwise; and
				any reference to the masculine includes a reference to the feminine
				and vice versa.</li>
			<li>Headings and captions are used for convenience only and will
				not affect the interpretation of the T&Cs.</li>
			<li>Any reference to a natural person will, unless repugnant to
				the context, include his legal heirs, executors and permitted
				assignees. Similarly, any reference to a juristic person such as XXX
				will, unless repugnant to the context, include its affiliates,
				successors and permitted assignees.</li>
		</ul>

		<h4>Eligibility</h4>

		<ul>
			<li>You will be ELIGIBLE to use the Services only when You
				fulfill the all of the following conditions:<br> <br> You
				have attained at least 18 (eighteen) years of age.<br> You are
				competent to enter into a contract under the Applicable Laws.
			</li>
			<li>You may avail the Services only if You fulfill the
				conditions as mentioned in 3.1.1 to 3.1.2 above. If You are not
				Eligible, please immediately abandon any and all attempts to
				register with Us or use Our Services.</li>
			<li>You acknowledge that We rely completely on the information
				provided by You and We Shall not be held liable if You or anyone who
				uses Your Account to access the Services on the Application is not
				Eligible to use the same.</li>

		</ul>

		<h4>Registration and Account</h4>

		<ul>
			<li>You understand and acknowledge that You can register on the
				Application only after complying with the requirements of Clause 3.1
				and through a valid Email ID. For clarity, the aforesaid requirement
				applies to members of Deemed Communities only to the extent of a
				valid email ID and does not apply to members of Open Communities.</li>
			<li>You will be required to enter Your Email ID on the
				Application following which a verification link would be sent to
				Your Email ID. Upon receipt of the verification link on Your Email
				ID, You Shall be required to click on the said link within 24
				(twenty four) hours of receiving the verification link in order to
				complete the aforesaid verification process. In the event of Your
				failure to click on the verification link within the above mentioned
				timeline, the same would lapse and You will have to repeat the
				process set out in this Clause 4.1. For clarity, the aforesaid
				requirement and process applies to members of Deemed Communities
				only to the extent of a valid email ID and does not apply to members
				of Open Communities.</li>
			<li>Upon completion of the verification process in accordance
				with Clause 4.1 above, You will be added to a Community or Deemed
				Community through which You can avail the Services offered on the
				Application.</li>
			<li>In order to use the Application, You are required to provide
				Registration Data to XXX on the Application. You Shall not
				impersonate someone else or provide account information, an email
				address or any other information that is not Your own. We Shall bear
				no liability for false, incomplete, old or incorrect Registration
				Data provided by You.</li>
			<li>In the event of any change in the said Registration Data,
				You agree to promptly update Your Registration Data on the Account
				so as to ensure that the communication We intend to send to You is
				promptly delivered to You and is not sent to any other entity/third
				party.</li>
			<li>XXX will store the Registration Data provided by You for
				contacting You for all Service related matters. You may promptly
				inform Us on any change in the Registration Data provided.</li>
			<li>We may send any Information to You to the mobile number or
				Original ID registered with Us as Registration Data.</li>
			<li>We reserve the right to suspend or terminate Your Account
				with immediate effect and for an indefinite period, if We have a
				reason to believe that the Registration Data or any other data
				provided by You is incorrect or false, or that the security of Your
				Account has been compromised in any way, or any other reason We may
				find it to just. We also reserve the right to suspend Your Account
				with immediate effect and for an indefinite period upon receipt of
				any complaint from Your Co Passenger and/or the CSP.</li>
			<li>It is Your responsibility to check to ensure You download
				the correct application for Your device. We are not liable if You do
				not have a compatible mobile device or if You download the wrong
				version of the Application for Your mobile device. We reserve the
				right to terminate the Service and the use of the Application should
				You be using the Service or Application with an incompatible or
				unauthorized device.</li>
			<li>We allow You to open only one Account in respect of one
				Email ID.</li>
			<li>You will not assign or otherwise transfer Your Account to
				any third party.</li>
			<li>In case of any unauthorized use of Your Account, You are to
				bring the same to Our notice promptly. In the event of the such
				unauthorized use, please immediately reach Us at
				support@XXXcabs.com.</li>
			<li>In case, You are unable to access Your Account, please
				inform Us at support@XXXcabs.com and make a written request for
				blocking Your Account. We will not be liable for any unauthorized
				transactions made through Your Account prior to the expiry of 72
				(seventy two) hours after You have made a request in writing for
				blocking Your Account except in case of Force Majeure events which
				are beyond Our reasonable control.</li>
			<li>NOTWITHSTANDING ANYTHING CONTAINED ANYWHERE IN THIS
				AGREEMENT THE REGISTRATION PROCESS CONTAINED IN CLAUSE 4 OF THESE
				T&C’s Shall NOT APPLY TO MEMBERS OF REGISTERED COMMUNITIES AND OPEN
				COMMUNITIES. THE REGISTRATION OF MEMBERS OF REGISTERED COMMUNITIES
				Shall BE GOVERNED BY THE TERMS OF THE SPECIAL SERVICE LEVEL
				ARRANGMENTS BETWEEN XXX AND THE RECOGNIZED ENTITIES. THE
				REGISTRATION OF MEMBERS OF OPEN COMMUNITIES Shall BE GOVERNED BY THE
				REGISTRATION REQUIREMENTS OF THE MOBILE APPLICATION XXXCABS ALONE.</li>


		</ul>


		<h4>Rights and Obligations: Do&#39;s & Don&#39;ts</h4>

		<ul>
			<li>A booking can be made only through the Application. You
				understand and undertake that the use of the Application is only for
				Your personal purpose. You Shall not be allowed to book rides on
				behalf of others, even if the person belongs to the same Community
				or Deemed Community or Registered Community.</li>
			<li>You Shall share Your ride only with members in the Community
				or Deemed Community or Registered Community or Open Community
				traveling along Your route. Such sharing Shall be subject to a
				permissible deviation and the extent of the said deviation Shall be
				determined by Us subject to Our sole discretion.</li>
			<li>You acknowledge that there may be a delay in dropping You at
				Your destination, as the CSP may take a longer route to pick Your
				Co-Passenger or may drop him/her first if his/her drop location
				happens to be located before Yours, and that You Shall have no claim
				against XXX in this regard.</li>
			<li>You Shall not use the Service for emergency hospital visits
				when You are in a condition of serious ill health or in any other
				case of emergency or urgency or any other situation of a similar
				nature. In the event that You choose to do so, You do so against the
				provisions of these T&Cs, and acknowledge that XXX Shall have no
				obligation in this regard.</li>
			<li>You may use the Service for airport drops, but You are best
				advised not to use the Service for the same. In the event that You
				choose to do so, You acknowledge that XXX Shall have no obligation
				in this regard.</li>
			<li>You are required to ensure that the Vehicle assigned to You
				in the manner provided in the T&Cs bears the same registration
				number and the registration details specified to You through the
				Application and/or SMS. You Shall not be allowed to exchange seats
				with a Customer who is assigned a seat in a different Vehicle.</li>
			<li>Customers Shall be dropped in order of their drop locations.</li>
			<li>You represent to XXX that while using the Service and during
				Your journey in the Vehicle, You Shall (a) behave in a disciplined
				and decent manner; (b) refrain from disturbing, misbehaving with, or
				in any other manner adversely affecting the quality of the journey
				of Your Co-Passengers and the CSP.</li>
			<li>No change in drop location Shall be allowed once XXX
				confirms the booking.</li>
			<li>You report promptly on time at the pick up location;</li>
			<li>You avoid talking loudly over the phone;</li>
			<li>You do not use foul language in the Vehicle;</li>
			<li>You do not play music in the Vehicle and/or cause any
				discomfort to Your Co Passenger(s) or the CSP;</li>
			<li>You do not share Your personal information with Your
				Co-Passenger(s) or the CSP. You maintain decorum and refrain from
				indulging in heated discussions or debate(s) with Your
				Co-Passenger(s) or the CSP;</li>
			<li>You avoid getting personal or overtly friendly with Your
				Co-Passenger(s) or CSP.</li>
			<li>You do not consume eatables (including drinking beverages)
				in the Vehicle;</li>
			<li>You keep Your belongings with You only. You do not utilize
				Your Co-Passenger’s seat for Your belongings;</li>
			<li>You do not indulge in any inappropriate behavior, verbal or
				otherwise, with Your Co-Passenger(s) or the CSP.</li>

		</ul>

		<h4>General Customer behaviour while using transport service
			through CSP</h4>

		<ul>
			<li>You Shall maintain reasonable behavior while utilizing the
				Services offered by the CSP.</li>
			<li>You Shall take full responsibility of Your items. In case of
				lost items during the journey, We will try to locate the items on a
				"best-effort" basis but We Shall not be responsible for the same in
				case of any losses or damages arising out of such lost items.</li>
			<li>You Shall not ask the CSP to break any
				Traffic/Transport/City Police and/or government rules for any
				purpose (especially reaching the destination earlier).</li>
			<li>You Shall not Pressurize the CSP to overload the boot space
				of the Vehicle with luggage. (The Customer Shall not be generally
				allowed to use the seating area of the Vehicle for placing any kind
				of luggage);</li>
			<li>You Shall not Request the CSP to halt at automated teller
				machines (ATM), shops, etc.</li>
			<li>You Shall not Consume alcohol and banned substances
				including drugs and psychotropic substances, smoke or consume any
				toxins while in the Vehicle.</li>


		</ul>
		<h4>Booking process</h4>
		<p>You may download the Application on Your device for availing
			the Service and the Service Shall be available only through the
			Application. For making a booking You will have to enter the
			destination on the booking screen of the Application. The pick-up
			address will be fixed to Your location at the time of making the
			booking and will be non-editable. Upon Your clicking the ‘Ride Now’
			tab, the booking confirmation screen will pop up which will display
			the ETT and the ride fare. If You agree to the travel time and the
			fare You will be required to hit the I Confirm icon.</p>


		<h4>Confirmation of booking</h4>
		<ul>
			<li>We Shall upon You clicking the I Confirm icon appearing at
				the bottom of Your screen, proceed to confirm or decline the booking
				based on the availability of Vehicles at the pickup time, which
				Shall be informed to You through the Application and/or via an SMS
				and email to your Original ID. Please note that You are required to
				check the drop point before You click the ‘I Confirm’ icon and make
				all alterations or changes to the desired drop location before
				clicking the I Confirm icon. In the event the booking is confirmed
				from Our end, You Shall check the booking details like ETA, pick up
				place and such other details as XXX may deem fit and if there are
				incorrect details, the same needs to be informed to Us immediately.
				You Shall be responsible for immediately reporting the errors, if
				any, that may have occurred in the information sent to You regarding
				booking confirmation. You Shall bear the consequences and damages
				for any delay that may be caused to You due to Your failure to check
				the confirmation SMS/email or failure to inform Us of the incorrect
				details immediately.</li>
			<li>You may, upon availing or attempting to avail the Services,
				receive SMS messages on Your mobile phone from Us regarding the
				following: <br> <br>(i) confirmation of booking -
				including driver name, vehicle license number and the ability to
				contact the CSP by telephone. <br>(ii) CSP declining Your
				booking. <br>(iii) total fees to be paid. However, the above
				list is not exhaustive in nature and You may receive additional and
				different messages from Us. You hereby understand, agree and consent
				to the receipt of such messages from Us.
			</li>
			<li>Upon Your booking being processed and confirmed via
				Application, e-mail and SMS, You will receive a timer notification
				on Your mobile phone after which You Shall be required to board the
				booked cab not later than 2 minutes of the notified pick up time.
				The CSP Shall be under no obligation whatsoever to wait for You at
				Your boarding point beyond the lapse of 2 (two) minutes of the
				pick-up time notified to You. In case of any delay caused by You in
				arriving at the pick-up point and the cab having proceeded without
				You, You Shall have no claim against XXX or the CSP and XXX Shall
				not be held liable in anyway whatsoever.<br> <br> For
				clarity, in the event, the Vehicle arrives later than the notified
				pick up time, the CSP Shall wait no longer than 2 minutes from his
				time of arrival at the notified pick up point. (Illustration: When
				the notified pick up time is 10:00 AM, the CSP Shall wait no longer
				than 10:02 AM. In the event, the CSP arrives at the notified pick up
				point at 10:10 AM, the CSP Shall wait no longer than 10:12 AM)
			</li>


		</ul>

		<h4>Payment</h4>

		<ul>
			<li><span>Cash payment</span><br> Cash payment Shall be
				made at the time of boarding the cab.Where You opt to pay by cash,
				You Shall make the cash payment at the time of boarding, such amount
				Shall be the amount specified to You at the time of booking
				confirmation. You will be required to pay the amount shared with You
				at the time of booking confirmation even if You opt to take a drop
				in between Your ride. The Customer Shall make best efforts and
				ensure that the Customer tenders exact change to the CSP.</li>
			<li><span>Online payment</span><br> Online payment for
				trips Shall be made to Us at the time You board the Vehicle through
				an e-wallet i.e. XXXMONEY powered by one or more third party payment
				processors (“Payment Processors”). When You choose to make an online
				payment, We Shall collect the fare on behalf of the driver or CSP
				who will be responsible for providing the transportation services.
				You acknowledge that collection of the fare on behalf of the driver
				or CSP in no way implies that the transportation services are being
				provided to You by Us. The processing of payments or credits, as
				applicable, in connection with Your use of the XXXMONEY will be
				subject to the terms, conditions, and privacy policies of the
				Payment Processor that We engage for the purpose. We will not be
				responsible for any errors by the Payment Processor. In connection
				with Your use of the Services, We will obtain certain transaction
				details, which We will use solely in accordance with its privacy
				policy. In the event the payment cannot be accepted through the
				method offered on the Application, You Shall be required to pay the
				fare of the transportation services in cash in terms of paragraph
				11.1 (Cash payment) above.</li>
			<li>We will generate an invoice on behalf of the driver
				servicing Your offer request, which will be sent across to Your
				Original ID after the completion of the Ride. The Invoice Shall be
				indicative of all applicable charges including but not limited to
				the surcharge, toll charges, right time charge, wait time charge,
				service tax. Any payment made is non-refundable.</li>
			<li>We may offer discounts and consequent deductions in the fare
				charged to the Customers at Our sole discretion. The invoice sent to
				the Customers Shall be indicative of such discounts. Notwithstanding
				anything contained herein, these discounts may be varied from time
				to time at the sole discretion of XXX.</li>
		</ul>

		<h4>Waiting policy</h4>
		<p>The CSP Shall wait only for 2 (Two) minutes for the Customer at
			the pick location. If the customer does not board within 2 (Two)
			minutes, then the CSP/XXX may cancel the trip and leave the pick-up
			location.</p>

		<h4>Cancellation policy</h4>
		<p>
			You may cancel the booking as early possible prior to the boarding of
			the Vehicle and commencement of the Ride, without any cancellation
			charges. In case, the money is deducted from Your XXXMONEY post a
			valid cancellation, the deducted amount towards trip fare would be
			refunded to You within 72 hours .<br>XXX/CSP may cancel the
			booking anytime prior to the payment of fare by the Customers to the
			CSP either through cash or through XXXMONEY. In the event of a
			deduction of fare from the Customers XXXMONEY post a valid
			cancellation by XXX/CSP, the amount so deducted Shall be refunded to
			the Customer within 72 hours. XXX does not warrant that a
			re-allotment of a Vehicle for the purposes of the Service under these
			T&Cs and a re-confirmation of booking Shall be made once a
			cancellation has been effected by either Parties.
		</p>

		<h4>Luggage policy</h4>
		<p>While using the Service You may not carry heavy luggage like
			suitcase, big bags etc. with You. However, You can carry handbags,
			backpacks etc. which You can easily carry along without taking much
			space or without using Your co-passenger seat space.</p>
		<h4>Charges</h4>

		<p>At present, We don’t charge You any fees for the use of Our
			Services. However, in the future, We reserve the right to charge fee
			and change Our policies from time to time. In particular, We may at
			Our sole discretion introduce new services and modify some or all of
			the existing Services offered on the Application. In such an event We
			reserve, without notice to You, the right to introduce fees for the
			new services offered or amend/introduce fees for existing Services,
			as the case may be. Changes to the Fee and related policies Shall
			automatically become effective immediately once implemented on the
			Application.</p>

		<h4>Other businesses</h4>
		<p>We do not take responsibility or liability for the actions,
			products, content and services on the Application, which are linked
			to affiliates and / or third party websites using Our APIs or
			otherwise. In addition, We may provide links to the third party
			websites of affiliated companies and certain other businesses for
			which, We assume no responsibility for examining or evaluating the
			products and services offered by them, and We do not warrant the
			offerings of, any of these businesses or individuals or the content
			of such third party website(s). We do not in any way endorse any
			third party website(s) or content thereof.</p>
		<h4>Links</h4>
		<p>You must not use on Your site or in any other manner any
			trademarks, service marks or any other materials appearing on the
			Application, including any logos or characters, without Our express
			written consent and consent of the owner of the mark or materials.
			You must not frame or otherwise incorporate into another third party
			website or present in conjunction with or juxtaposed against such a
			website any of the content or other materials on the Application
			without Our prior written consent.</p>

		<h4>Disclaimers</h4>

		<ul>
			<li>Except for Our limited role in providing You cab booking
				facility that You authorize or initiate, We are not involved in any
				underlying transaction between You, any other Customer, CSPs or
				other third party. We are not a selling agent in relation to any
				sale of goods or services to You by any CSP or any other third
				party. We Shall not be liable for the quality, safety, reliability,
				legality, delivery or any other aspect of any service that You may
				avail using the Application. Your use of the Service is at Your sole
				risk. The Service is provided on an "as is" and "as available"
				basis. We do not guarantee and do not promise any specific results
				from use of the Application and/or the Services, including the
				ability to avail the Services at any particular location or time. We
				disclaim all warranties of any kind whether express or implied
				including without limitation, any representation or warranty for
				accuracy, availability, continuity, uninterrupted access,
				timeliness, sequence, quality, performance, security,
				merchantability, fitness for any particular purpose,
				non-infringement or completeness. Without prejudice to the forgoing
				paragraph, We do not warrant that:<br> <br>This
				Application will be constantly available, or available at all; or <br>
				<br> The information on this Application is complete, true,
				accurate or non-misleading; or <br> <br>This Application;
				information, Content, materials, product (including software) or
				services included on or otherwise made available to You through the
				Application; their servers; or electronic communication sent from Us
				are free of viruses or other harmful components; or <br> <br>
				Content on the Application constitutes, or is meant to constitute,
				advice of any kind;
			</li>
			<li>Your correspondence or business dealings with, or
				participation in promotions of, third party advertisers found on or
				through the Application, including payment and delivery of related
				goods or services, and any other terms, conditions, warranties or
				representations associated with such dealings, are solely between
				You and such third party advertiser. We Shall not be responsible or
				liable for any loss or damage of any sort incurred as the result of
				any such dealings or as the result of the presence of such third
				party advertisers on the Application.</li>
			<li>XXX Shall not be responsible or liable for any loss or
				damage, howsoever caused or suffered by the Customer arising out of
				the use of cab service offered by CSP or due to the failure of CSP
				to provide Services to the Customer for any reason whatsoever
				including but not limited to the Customer's non-compliance with the
				Services' recorded voice instructions, malfunction, partial or total
				failure of any network terminal, data processing system, computer
				tele-transmission or telecommunications system or other
				circumstances whether or not beyond the control of XXX or any person
				or any organization involved in the above mentioned systems.</li>
			<li>You acknowledge that while XXX employs certain quality
				control measures, XXX does not, and cannot exercise control over the
				quality or safety of the transportation that is made use of by You
				through the Services.</li>
			<li>XXX will not be liable for any damages of any kind arising
				from the use of the service offered by the CSP including, but not
				limited to direct, indirect, incidental, punitive, and consequential
				damages.</li>
			<li>XXX will take all reasonable measures to ensure that CSP
				should fulfill his duty properly but there may be exceptions and if
				any passenger misses the train or flight or bus, XXX will not be
				held liable for any such compensation. The Customer is advised to
				make alternate arrangement in case the cab has not reached due to
				any reason.</li>
			<li>The ride services, and any claim resulting from the same,
				while requested through the Application, remains the responsibility
				of the CSPs and XXX Shall not be liable for any conduct of the CSPs.
				XXX encourages You to notify any complaints that You may have
				against the driver of any Cab that You may have hired using the
				XXX’s platform</li>
			<li>XXX is not responsible for the conduct, whether online or
				offline, of any other user of the Application or Services. You are
				solely responsible for Your interactions with other users, whether
				drivers or Co-Passengers. By using the Application and the Services,
				You agree to accept such risks and acknowledge that XXX is not
				responsible for the acts or omissions of other users.</li>
			<li>The Customer acknowledges that in the event the Customer
				does not avail the Service(s) in the Vehicle allocated to him/her by
				XXX and/or the Customer exchanges the seat allocated to him/her with
				a seat allocated to another Customer in another Vehicle, the
				Customer Shall do so at its own and sole risk. XXX Shall not bear
				any liability arising out of or in connection with such acts on the
				part of the Customers.</li>
			<li>All the vehicles registered with XXX platform are
				continuously tracked using GPS for security reasons only. It is
				expressly made clear to You hereby that XXX does not own any cabs
				nor does it directly or indirectly employ any of the CSPs for the
				cabs. XXX disclaims any and all liability in respect of the CSPs and
				the cabs alike.</li>

			<li>The location data made available on the Application is basic
				is nature, and meant to provide guidance to drivers only. You
				acknowledge that it is not intended to be relied upon in situations
				where precise location information is required, or where erroneous,
				inaccurate or incomplete data may lead to death, personal injury,
				property or environmental damage. XXX does not guarantee the
				availability, accuracy, completeness, reliability, or timeliness of
				location data displayed.</li>
			<li>We do not authorize anyone to make a warranty on Our behalf
				and You may not rely on any statement of warranty as a warranty by
				Us.</li>
			<li>XXX and its representatives, officers, employees, agents and
				contractors Shall not be liable for any loss, damage, claim,
				expense, cost (including legal costs) or liability arising directly
				or indirectly from Your use or non-use of the Service or the
				Application, or Your reliance upon the Service or the information
				contained upon the Application (whether arising from XXX or any
				other person's negligence or otherwise).</li>
			<li>We do not warrant that Your use of the Application or
				Services will be accurate, complete, reliable, current, secure,
				uninterrupted, always available, or error-free, or will meet Your
				requirements, that any defects in the Application will be corrected,
				or that the Application is free of viruses or other harmful
				components. We disclaim liability for, and no warranty is made with
				respect to, connectivity and availability of the Application or
				Services.</li>

		</ul>
	</div>

	<div class="privacyHeader">
		<h1>PRIVACY POLICY</h1>
		<hr>
	</div>

	<div class="privacyPanel">

		<p>
			Your privacy matters to ANI Technologies Private Limited (the
			“Company”, “we”, “XXX”, or “us”). This Privacy Policy explains how we
			collect, process, use, share and protect information about you. It
			also tells you how you can access and update your information and
			make certain choices about how your information is used. The Privacy
			Policy covers both “online” (e.g., web and mobile services, including
			any websites operated by us such as https://www.XXXcabs.com/ or
			Mobile Application, however accessed and/or used, whether via
			personal computers, mobile devices or otherwise) and offline (e.g.,
			collection of data through mailings, telephone, or in person)
			activities owned, operated, provided, or made available by the
			Company. Our online and offline activities, in relation to
			facilitation of taxi hire services through a network of third party
			drivers and taxi operators, are collectively referenced as the
			“Services”. This Privacy Policy also applies to your use of
			interactive features or downloads that:<br> <br> (i) we own
			or control.<br> <br> (ii) are available through the
			Services.<br> <br> (iii) interact with the Services and
			post or incorporate this Privacy Policy.<br> <br> BY
			ACCEPTING THE CUSTOMER TERMS AND CONDITIONS, YOU AGREE TO THE TERMS
			OF THIS PRIVACY POLICY.<br> <br>Please review the following
			carefully so that you understand our privacy practices. If you do not
			agree to this Privacy Policy, do not accept the Customer Terms and
			Conditions or use our Services. This Privacy Policy is incorporated
			by reference into the Customer Terms and Conditions.<br> <br>
			If you have questions about this Privacy Policy, please contact us
			through email address provided on our website and/ or Mobile
			Application.
		</p>

		<h4>DEFINITIONS</h4>
		<p>
			Unless otherwise provided in this Privacy Policy, the terms
			capitalized in the Privacy Policy Shall have the meaning as provided
			hereunder: <br> <br> <span>Co-branded Services</span><br>
			Shall have the meaning assigned to the term in paragraph 4(c) hereto.
			<br> <br> <span>Device</span><br> Shall mean computer,
			mobile or other device used to access the Services. <br> <br>
			<span>Device Identifier</span><br> Shall mean IP address or
			other unique identifier for the Device. <br> <br> <span>Mobile
				Application</span><br> Shall mean application provided by us on the
			Device to access the Services. <br> <br> <span>Mobile
				Device Information</span><br> Shall have the meaning assigned to the
			term in paragraph 2(d)(ii) hereto. <br> <br> <span>Promotion</span><br>
			Shall mean any contest and other promotions offered by us. <br>
			<br> <span>Protected Information</span><br> Shall mean such
			categories of information that could reasonably be used to identify
			you personally, including your name, e-mail address, and mobile
			number. <br> <br> <span>TFS</span><br> Shall mean
			Serendipity InfXXXbs Private Limited, a company incorporated under
			the Companies Act 1956, and having its corporate office at 3rd Floor,
			Salarpuria Tower 2, No. 32, Luskur Hosur Road, Next to Forum Mall,
			Bangalore- 560095 which expression Shall, unless it be repugnant to
			the context or meaning thereof, be deemed to mean and include all our
			successors, affiliates and permitted assigns. <br> <br> <span>TPSP</span><br>
			Shall mean a third party service provider. <br> <br> <span>Usage
				Information</span><br> Shall have the meaning assigned to the term in
			paragraph 2(b)(i) hereto.

		</p>
		<h4>WHAT INFORMATION DO WE COLLECT?</h4>
		<p>
			<label>INFORMATION YOU PROVIDE TO US</label><br> <br> We
			may ask you to provide us with certain Protected Information. We may
			collect this information through various means and in various places
			through the Services, including account registration forms, contact
			us forms, or when you otherwise interact with us. When you sign up to
			use the Services, you create a user profile. We shall ask you to
			provide only such Protected Information which is for lawful purpose
			connected with our Services and necessary to be collected by us for
			such purpose.<br> <br> The current data fields that might
			be requested for are:
		</p>

		<ul>
			<li>Email</li>
			<li>Password</li>
			<li>Name</li>
			<li>Address</li>
			<li>Mobile phone Number</li>
			<li>Zip Code</li>

		</ul>
		<p>
			<label> INFORMATION WE COLLECT AS YOU ACCESS AND USE OUR
				SERVICES</label>
		</p>

		<ul>
			<li>In addition to any Protected Information or other
				information that you choose to submit to us, we and our TPSP may use
				a variety of technologies that automatically (or passively) collect
				certain information whenever you visit or interact with the Services
				(“Usage Information”). This Usage Information may include the
				browser that you are using, the URL that referred you to our
				Services, all of the areas within our Services that you visit, and
				the time of day, among other information. In addition, we collect
				your Device Identifier for your Device. A Device Identifier is a
				number that is automatically assigned to your Device used to access
				the Services, and our computers identify your Device by its Device
				Identifier.</li>
			<li>In case of booking via call centre, XXX may record calls for
				quality and training purposes.</li>
			<li>In addition, tracking information is collected as you
				navigate through our Services, including, but not limited to
				geographic areas. The driver’s mobile phone will send your GPS
				coordinates, during the ride, to our servers. Most GPS enabled
				mobile devices can define one’s location to within 50 feet.</li>
			<li>Usage Information may be collected using a cookie. If you do
				not want information to be collected through the use of cookies,
				your browser allows you to deny or accept the use of cookies.
				Cookies can be disabled or controlled by setting a preference within
				your web browser or on your Device. If you choose to disable cookies
				or flash cookies on your Device, some features of the Services may
				not function properly or may not be able to customize the delivery
				of information to you. The Company cannot control the use of cookies
				(or the resulting information) by third parties, and use of third
				party cookies is not covered by our Privacy Policy.</li>

		</ul>

		<p>
			<label> INFORMATION THIRD PARTIES PROVIDE ABOUT YOU</label><br>
			<br> We may, from time to time, supplement the information we
			collect about you through our website or Mobile Application or
			Services with outside records from third parties.<br> <br>
			<label> INFORMATION COLLECTED BY MOBILE APPLICATIONS</label>

		</p>

		<ul>
			<li>Our Services are primarily provided through the Mobile
				Application. We may collect and use technical data and related
				information, including but not limited to, technical information
				about your device, system and application software, and peripherals,
				that is gathered periodically to facilitate the provision of
				software updates, product support and other services to you (if any)
				related to such Mobile Applications.</li>
			<li>When you use any of our Mobile Applications, the Mobile
				Application may automatically collect and store some or all of the
				following information from your mobile device (“Mobile Device
				Information”), in addition to the Device Information, including
				without limitation:</li>
			<li>Your mobile operating system</li>
			<li>The type of mobile internet browsers you are using</li>
			<li>Your geolocation</li>
			<li>Information about how you interact with the Mobile
				Application and any of our web sites to which the Mobile Application
				links, such as how many times you use a specific part of the Mobile
				Application over a given time period, the amount of time you spend
				using the Mobile Application, how often you use the Mobile
				Application, actions you take in the Mobile Application and how you
				engage with the Mobile Application</li>

		</ul>
		<h4>USE OF INFORMATION COLLECTED</h4>
		<p></p>
		<ul>
			<li>Our primary goal in collecting your information is to
				provide you with an enhanced experience when using the Services. We
				use your information to closely monitor which features of the
				Services are used most, to allow you to view your trip history, rate
				trips, and to determine which features we need to focus on
				improving, including usage patterns and geographic locations to
				determine where we should offer or focus services, features and/or
				resources.</li>
			<li>Based upon the Protected Information you provide us when
				registering for an account, we will send you a welcoming email to
				verify your username and password.</li>
			<li>We use the information collected from our Mobile Application
				so that we are able to serve you the correct app version depending
				on your device type, for troubleshooting and in some cases,
				marketing purposes</li>
			<li>We use your Internet Protocol (IP) address to help diagnose
				problems with our computer server, and to administer our web
				site(s). Your IP address is used to help identify you, but contains
				no personal information about you.</li>
			<li>We will send you strictly service-related announcements on
				rare occasions when it is necessary to do so. For instance, if our
				Services are temporarily suspended for maintenance, we might send
				you an email. If you do not wish to receive them, you have the
				option to deactivate your account.</li>
			<li>We may use the information obtained from you to prevent,
				discover and investigate viXXXtions of this Privacy Policy or any
				applicable terms of service or terms of use for the Mobile
				Application, and to investigate fraud, chargeback or other matters.</li>
			<li>In addition, we may use your Protected Information or Usage
				Information that we collect about you: (1) to provide you with
				information or services or process transactions that you have
				requested or agreed to receive including to send you electronic
				newsletters, or to provide you with special offers or promotional
				materials on behalf of us or third parties; (2) to enable you to
				participate in a variety of the Services’ features such as online or
				mobile entry sweepstakes, contests or other promotions; (3) to
				contact you with regard to your use of the Services and, in our
				discretion, changes to the Services and/or the Services’ policies;
				(4) for internal business purposes; (5) for inclusion in our data
				analytics; and (6) for purposes disclosed at the time you provide
				your information or as otherwise set forth in this Privacy Policy.</li>
			<li>We may use the information collected from you for targeted
				advertising. This involves using information collected on an
				individual's web or mobile browsing behavior such as the pages they
				have visited or the searches they have made. This information is
				then used to select which advertisements should be displayed to a
				particular individual on websites other than our web site(s). The
				information collected is only linked to an anonymous cookie ID
				(alphanumeric number); it does not include any information that
				could be linked back to a particular person, such as their name,
				address or credit card number.</li>
			<li>We use that geo-location information for various purposes,
				including for you to be able to view the drivers in your area that
				are close to your location, for you to set your pick up location,
				for the drivers to identify the pick up location, to send you
				promotions and offers, and to allow you (if you choose through any
				features we may provide) to share this information with other
				people.</li>

		</ul>

		<h4>HOW AND WHEN DO WE DISCLOSE INFORMATION TO THIRD PARTIES</h4>

		<p>
			We do not sell, share, rent or trade the information we have
			collected about you, other than as disclosed within this Privacy
			Policy or at the time you provide your information. Following are the
			situations when information may be shared: <br> <br> <label>
				WHEN YOU AGREE TO RECEIVE INFORMATION FROM THIRD PARTIES.</label><br> <br>
			You may be presented with an opportunity to receive information
			and/or marketing offers directly from third parties. If you do agree
			to have your Protected Information shared, your Protected Information
			will be disclosed to such third parties and all information you
			disclose will be subject to the privacy policy and practices of such
			third parties. We are not responsible for the privacy policies and
			practices of such third parties and, therefore, you should review the
			privacy policies and practices of such third parties prior to
			agreeing to receive such information from them. If you later decide
			that you no longer want to receive communication from a third party,
			you will need to contact that third party directly. <br> <br>
			<label> THIRD PARTIES PROVIDING SERVICES ON OUR BEHALF</label><br>
			<br> We use third party companies and individuals to facilitate
			our Services, provide or perform certain aspects of the Services on
			our behalf – such as drivers and companies they work for to provide
			the Services, other third parties including TFS to host the Services,
			design and/or operate the Services’ features, track the Services’
			analytics, process payments, engage in anti-fraud and security
			measures, provide customer support, provide geo-location information
			to our drivers, enable us to send you special offers, host our job
			application form, perform technical services (e.g., without
			limitation, maintenance services, database management, web analytics
			and improvement of the Services‘ features), or perform other
			administrative services. These third parties will have access to user
			information, including Protected Information to only carry out the
			services they are performing for you or for us. Each of these third
			parties including TFS are required to ensure the same level of data
			protection as us and are obligated not to disclose or use Protected
			Information for any other purpose. Analytics TPSPs may set and access
			their own cookies, web beacons and embedded scripts on your Device
			and they may otherwise collect or have access to information about
			you, including non-personally identifiable information. We use a
			third party hosting provider who hosts our support section of our
			website. Information collected within this section of our website by
			such third party is governed by our Privacy Policy. <br> <br>
			<label> CO-BRANDED SERVICES.</label><br> <br> Certain
			aspects of the Services may be provided to you in association with
			third parties (“Co-Branded Services”) such as sponsors and charities,
			and may require you to disclose Protected Information to them. Such
			Co-Branded Services will identify the third party. If you elect to
			register for products and/or services through the Co-Branded
			Services, you shall have deemed to consent to providing your
			information to both us and the third party. Further, if you sign-in
			to a Co-Branded Service with a username and password obtained through
			our Services, your Protected Information may be disclosed to the
			identified third parties for that Co-Branded Service and will be
			subject to their posted privacy policies. <br> <br> <label>
				CONTESTS AND PROMOTIONS</label><br> <br> We may offer Promotions
			through the Services that may require registration. By participating
			in a Promotion, you are agreeing to official rules that govern that
			Promotion, which may contain specific requirements of you, including,
			allowing the sponsor of the Promotion to use your name, voice and/or
			likeness in advertising or marketing associated with the Promotion.
			If you choose to enter a Promotion, you agree that your Protected
			Information may be disclosed to third parties or the public in
			connection with the administration of such Promotion, including, in
			connection with winner selection, prize fulfillment, and as required
			by law or permitted by the Promotion’s official rules, such as on a
			winners list. <br> <br> <label> ADMINISTRATIVE AND
				LEGAL REASONS</label><br> <br> We cooperate with Government and
			law enforcement officials and private parties to enforce and comply
			with the law. Thus, we may access, use, preserve, transfer and
			disclose your information (including Protected Information, IP
			address, Device Information or geo-location data), to Government or
			law enforcement officials or private parties as we reasonably
			determine is necessary and appropriate: (i) to satisfy any applicable
			law, regulation, subpoenas, Governmental requests or legal process;
			(ii) to protect and/or defend the Terms and Conditions for online and
			mobile Services or other policies applicable to any online and mobile
			Services, including investigation of potential viXXXtions thereof;
			(iii) to protect the safety, rights, property or security of the
			Company, our Services or any third party; (iv) to protect the safety
			of the public for any reason; (v) to detect, prevent or otherwise
			address fraud, security or technical issues; and /or (vi) to prevent
			or stop activity we may consider to be, or to pose a risk of being,
			an illegal, unethical, or legally actionable activity. <br> <br>
			<label> WHEN YOU SHARE INFORMATION</label><br> <br>
			Protected Information may be collected and shared with third-parties
			if there is content from the Mobile Application that you specifically
			and knowingly upload to, share with or transmit to an email
			recipient, online community, website, or to the public, e.g. uploaded
			photos, posted reviews or comments, or information about you or your
			ride that you choose to share with others through features which may
			be provided on our Services. This uploaded, shared or transmitted
			content will also be subject to the privacy policy of the email,
			online community website, social media or other platform to which you
			upload, share or transmit the content. <br> <br> <label>
				BUSINESS TRANSFER</label><br> <br> We may share your information,
			including your Protected Information and Usage Information with our
			parent, subsidiaries and affiliates for internal reasons. We also
			reserve the right to disclose and transfer all such information: (i)
			to a subsequent owner, co-owner or operator of the Services or
			applicable database; or (ii) in connection with a corporate merger,
			consolidation, restructuring, the sale of substantially all of our
			membership interests and/or assets or other corporate change,
			including, during the course of any due diligence process.
		</p>

		<h4>THIRD PARTY CONTENT AND LINKS TO THIRD PARTY SERVICES</h4>

		<p>The Services may contain content that is supplied by a third
			party, and those third parties may collect website usage information
			and your Device Identifier when web pages from any online or mobile
			Services are served to your browser. In addition, when you are using
			the Services, you may be directed to other sites or applications that
			are operated and controlled by third parties that we do not control.
			We are not responsible for the privacy practices employed by any of
			these third parties. For example, if you click on a banner
			advertisement, the click may take you away from one of our websites
			onto a different web site. These other web sites may send their own
			cookies to you, independently collect data or solicit Protected
			Information and may or may not have their own published privacy
			policies. We encourage you to note when you leave our Services and to
			read the privacy statements of all third party web sites or
			applications before submitting any Protected Information to third
			parties.</p>

		<h4>SOCIAL MEDIA FEATURES AND WIDGETS</h4>
		<p>Our online and mobile Services may include social media
			features, such as the Facebook Like button, and widgets such as a
			“Share This” button, or interactive mini-programs that run on our
			online and mobile Services. These features may collect your IP
			address, photograph, which page you are visiting on our online or
			mobile Services, and may set a cookie to enable the feature to
			function properly. Social media features and widgets are either
			hosted by a third party or hosted directly on our online Services.
			Your interactions with these features and widgets are governed by the
			privacy policy of the company providing them.</p>
		<h4>INFORMATION COLLECTED BY DRIVERS</h4>
		<p>This Privacy Policy shall not cover the usage of any information about
		you which is obtained by the driver or the company to which the driver
		belongs, while providing you a ride on a cab booked using the
		Services, or otherwise, which is not provided by us.</p>
		<h4>CHANGE OF INFORMATION AND CANCELLATION OF ACCOUNT</h4>
		<p>[a] You are responsible for maintaining the accuracy of the
		information you submit to us, such as your contact information
		provided as part of account registration. If your Protected
		Information changes, or if you no longer desire our Services, you may
		correct, delete inaccuracies, or amend information by making the
		change on our member information page or by contacting us through
		through email address mentioned on our website or Mobile Application.
		We will make good faith efforts to make requested changes in our then
		active databases as soon as reasonably practicable.<br><br> [b] You may also
		cancel or modify your communications that you have elected to receive
		from the Services by following the instructions contained within an
		e-mail or by logging into your user account and changing your
		communication preferences.<br><br>  [c] If upon modifying or changing the
		information earlier provided to Us, we find it difficult to permit
		access to our Services to you due to insufficiency/ inaccuracy of the
		information, we may, in our sole discretion terminate your access to
		the Services by providing you a written notice to this effect on your
		registered email id.<br><br>  [d] If you wish to cancel your account or request
		that we no longer use your information to provide you services,
		contact us through through email address mentioned on the trip bill
		received. We will retain your Protected Information and Usage
		Information (including geo-location) for as long as your account with
		the Services is active and as needed to provide you services. Even
		after your account is terminated, we will retain your Protected
		Information and Usage Information (including geo-location, trip
		history, and transaction history) as needed to comply with our legal
		and regulatory obligations, resolve disputes, conclude any activities
		related to cancellation of an account, investigate or prevent fraud
		and other inappropriate activity, to enforce our agreements, and for
		other business reason. After a period of time, your data may be
		anonymized and aggregated, and then may be held by us as long as
		necessary for us to provide our Services effectively, but our use of
		the anonymized data will be solely for analytic purposes.</p>
		<h4>SECURITY</h4>
		<p>The Protected Information and Usage Information we collect is securely
		stored within our databases, and we use standard, industry-wide,
		commercially reasonable security practices such as encryption.</p>

	</div>














	<footer>
	<h4>WE ARE HERE TO OFFER</h4>

	<ul>
		<li>24 / 7 Cab Service To Any Where Around The City</li>
		<li>Sending Booking Alert By SMS</li>
		<li>GPS Tracking System For Location Guessing</li>
		<li>Instant Printed Bills In Car On Departure</li>
		<li>Magazine And News Papers For Reading On Ride</li>
		<li>Credit And Debit Card Payment Available</li>

	</ul>
	<h4 style="position: absolute; top: 0px; right: 300px;">ABOUT US.</h4>
	<table>
		<tr>
			<td><img src="Images\addr.png" width="32dp" height="32dp"></td>
			<td>233 Shoreditch High Street Shoreditch,London</td>
		</tr>
		<tr>
			<td><img src="Images\cont.png" width="32dp" height="32dp"></td>
			<td>Customer Support :<br>+ 124 45 76 678
			</td>
		</tr>
		<tr>
			<td><img src="Images\email.png" width="32dp" height="32dp"></td>
			<td>Email :<br> mail@NationalCab.com
			</td>
		</tr>
	</table>
	<hr>
	<h5>Copyright &#169 2010 - 2016. All Rights Reserved</h5>
	</footer>
	
	
	<script type="text/javascript">
	$(window).scroll(function() {

		if ($(this).scrollTop() > 250) {
			$('.back-to-top').fadeIn();

		} else {
			$('.back-to-top').fadeOut();
		}
	});
	$('.back-to-top').click(function(event) {
		event.preventDefault();
		$('html,body').animate({
			scrollTop : 0
		}, 1000);
		return false;
	});
	</script>
	<script src="js/jQuery.scrollSpeed.js"></script>
<script>
$(function() {  

    jQuery.scrollSpeed(200, 1000);

});
</script>
</body>
</html>